#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

userid=`whoami`

cd /var/lib/stickshift/$userid/app-root/runtime/repo/php/
mkdir files
chmod 777 files
